# http
http:
  routers:
    dashboard:
      rule: "Host(`traefik.dev`)"
      entryPoints:
        - "websecure"
      service: "api@internal"
      tls: {}
    service1:
      rule: "Host(`service1.dev`)"
      service: service1
      entryPoints:
        - "websecure"
      tls: {}
  services:
    service1:
      loadBalancer:
        servers:
          - url: "http://service1:80"
# tcp
tcp:
  routers:
    service2:
      rule: "HostSNI(`service2.dev`)"
      entryPoints:
        - "websecure"
      service: service2
      tls:
        passthrough: true
  services:
    service2:
      loadBalancer:
        servers:
          - address: "service2:443"

