services:
  traefik:
    image: traefik:v3.4
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./certs:/certs:ro
      - ./dynamic:/dynamic:ro
    networks:
      - traefik

networks:
  traefik:
    external: true
